# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: "vi"
pipeline:
  - name: HFTransformersNLP
    model_name: "bert"
  # - name: "SpacyTokenizer"
  # # Flag to check whether to split intents
  #   "intent_tokenization_flag": False
  #   # Symbol on which intent should be split
  #   "intent_split_symbol": "_"
  #   # Regular expression to detect tokens
  #   "token_pattern": None
  - name: "LanguageModelTokenizer"
    # Flag to check whether to split intents
    "intent_tokenization_flag": False
    # Symbol on which intent should be split
    "intent_split_symbol": "_"
  - name: RegexFeaturizer
#   "case_sensitive": True
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    number_of_transformer_layers: 5
    transformer_size: 100
    epochs: 300
    batch_strategy: sequence
    embedding_dimension: 30
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 200

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
    max_history: 5
  - name: TEDPolicy
    max_history: 5
    epochs: 200
  - name: MappingPolicy
  - name: FormPolicy
  - name: "RulePolicy"
    core_fallback_threshold: 0.3
    core_fallback_action_name: action_default_fallback
    enable_fallback_prediction: true
    restrict_rules: true
    check_for_contradictions: true