# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: "en"

pipeline:
- name: "WhitespaceTokenizer"
  # Flag to check whether to split intents
  "intent_tokenization_flag": False
  # Symbol on which intent should be split
  "intent_split_symbol": "_"
  # Regular expression to detect tokens
  "token_pattern": None
- name: "RegexFeaturizer"
  # Text will be processed with case sensitive as default
  "case_sensitive": True
#- name: "CRFEntityExtractor"
- name: "CountVectorsFeaturizer"
  # Analyzer to use, either 'word', 'char', or 'char_wb'
  "analyzer": "char_wb"
  # Set the lower and upper boundaries for the n-grams
  "min_ngram": 1
  "max_ngram": 5
  # Whether to use a shared vocab
  "use_shared_vocab": True
- name: "DIETClassifier"
  epochs: 500
- name: FallbackClassifier
  threshold: 0.6
- name: "EntitySynonymMapper"
- name: "ResponseSelector"

  
# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 10
    random_seed: 42
    epochs: 200
  - name: RulePolicy
