# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: "vi"

pipeline:
- name: HFTransformersNLP
  # Name of the language model to use
  model_name: "bert"
  # Pre-Trained weights to be loaded
  model_weights: "rasa/LaBSE"
  cache_dir: null
- name: "LanguageModelTokenizer"
  # Flag to check whether to split intents
  "intent_tokenization_flag": False
  # Symbol on which intent should be split
  "intent_split_symbol": "_"
- name: "RegexFeaturizer"
  # Text will be processed with case sensitive as default
  "case_sensitive": True
- name: LanguageModelFeaturizer
  model_name: "bert"
  model_weights: "rasa/LaBSE"
  cache_dir: null
- name: "DIETClassifier"
  epochs: 600
- name: FallbackClassifier
  threshold: 0.65
  epochs: 200
- name: "EntitySynonymMapper"
- name: "ResponseSelector"

  
# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 3
    random_seed: 42
    epochs: 100
  - name: RulePolicy
