# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: "vi"

pipeline:
- name: HFTransformersNLP
  # Name of the language model to use
  model_name: "roberta"
  # Pre-Trained weights to be loaded
  model_weights: "roberta-base"
  cache_dir: null
- name: "LanguageModelTokenizer"
  model_name: "roberta"
  # Pre-Trained weights to be loaded
  model_weights: "roberta-base"
- name: LanguageModelFeaturizer
  model_name: "roberta"
  model_weights: "roberta-base"
  cache_dir: null
- name: RegexFeaturizer
- name: "DIETClassifier"
  entity_recognition: False
  epochs: 400
- name: FallbackClassifier
  threshold: 0.7
- name: RegexEntityExtractor
- name: "CRFEntityExtractor"
  "BILOU_flag": True
  # features to extract in the sliding window
  "features": [
    ["low", "title", "upper"],
    [
      "bias",
      "low",
      "prefix5",
      "prefix2",
      "suffix5",
      "suffix3",
      "suffix2",
      "upper",
      "title",
      "digit",
      "pattern",
    ],
    ["low", "title", "upper"],
  ]
  # The maximum number of iterations for optimization algorithms.
  "max_iterations": 50
  # weight of the L1 regularization
  "L1_c": 0.1
  # weight of the L2 regularization
  "L2_c": 0.1
- name: "EntitySynonymMapper"
- name: "ResponseSelector"

  
# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 3
    random_seed: 42
    epochs: 100
  - name: RulePolicy

